import Politician from '../models/Politician';

const politiciansData = [
  // ==================== GOVERNADOR ====================
  {
    name: 'Wanderlei Barbosa',
    role: 'governador' as const,
    party: 'Republicanos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Governador do Tocantins - Republicanos',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },

  // ==================== PREFEITO ====================
  {
    name: 'Eduardo Siqueira Campos',
    role: 'prefeito' as const,
    party: 'Podemos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Prefeito de Palmas - Podemos',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },

  // ==================== SENADORES ====================
  {
    name: 'Eduardo Gomes',
    role: 'senador' as const,
    party: 'PL',
    city: 'Palmas',
    state: 'TO',
    bio: 'Senador do Tocantins - PL',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Irajá Abreu',
    role: 'senador' as const,
    party: 'PSD',
    city: 'Palmas',
    state: 'TO',
    bio: 'Senador do Tocantins - PSD',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Professora Dorinha Seabra',
    role: 'senador' as const,
    party: 'União Brasil',
    city: 'Palmas',
    state: 'TO',
    bio: 'Senadora do Tocantins - União Brasil',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },

  // ==================== DEPUTADOS FEDERAIS ====================
  {
    name: 'Alexandre Guimarães',
    role: 'dep_federal' as const,
    party: 'MDB',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Federal do Tocantins - MDB',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Antonio Andrade',
    role: 'dep_federal' as const,
    party: 'Republicanos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Federal do Tocantins - Republicanos',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Carlos Henrique Gaguim',
    role: 'dep_federal' as const,
    party: 'União Brasil',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Federal do Tocantins - União Brasil',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Eli Borges',
    role: 'dep_federal' as const,
    party: 'PL',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Federal do Tocantins - PL',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Filipe Martins',
    role: 'dep_federal' as const,
    party: 'PL',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Federal do Tocantins - PL',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Ricardo Ayres',
    role: 'dep_federal' as const,
    party: 'Republicanos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Federal do Tocantins - Republicanos',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Tiago Dimas',
    role: 'dep_federal' as const,
    party: 'Podemos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Federal do Tocantins - Podemos',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Vicentinho Júnior',
    role: 'dep_federal' as const,
    party: 'PSDB',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Federal do Tocantins - PSDB',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },

  // ==================== DEPUTADOS ESTADUAIS ====================
  {
    name: 'Júnior Geo',
    role: 'dep_estadual' as const,
    party: 'PSDB',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - PSDB',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Léo Barbosa',
    role: 'dep_estadual' as const,
    party: 'Republicanos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - Republicanos',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Ivory de Lira',
    role: 'dep_estadual' as const,
    party: 'PL',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - PL',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Gutierres Torquato',
    role: 'dep_estadual' as const,
    party: 'PDT',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - PDT',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Jair Farias',
    role: 'dep_estadual' as const,
    party: 'MDB',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - MDB',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Eduardo do Dertins',
    role: 'dep_estadual' as const,
    party: 'PP',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - PP',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Claudia Lelis',
    role: 'dep_estadual' as const,
    party: 'PV',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputada Estadual do Tocantins - PV',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Valderez Castelo Branco',
    role: 'dep_estadual' as const,
    party: 'PP',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputada Estadual do Tocantins - PP',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Amélio Cayres',
    role: 'dep_estadual' as const,
    party: 'Republicanos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - Republicanos',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Fabion Gomes',
    role: 'dep_estadual' as const,
    party: 'PL',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - PL',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Jorge Frederico',
    role: 'dep_estadual' as const,
    party: 'PP',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - PP',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Issam Saado',
    role: 'dep_estadual' as const,
    party: 'PL',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - PL',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Ataídes Oliveira',
    role: 'dep_estadual' as const,
    party: 'Pros',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - Pros',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Olyntho Neto',
    role: 'dep_estadual' as const,
    party: 'Republicanos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - Republicanos',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Rérisson de Castro',
    role: 'dep_estadual' as const,
    party: 'PSD',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - PSD',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Vanda Monteiro',
    role: 'dep_estadual' as const,
    party: 'PSD',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputada Estadual do Tocantins - PSD',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Paulo Mourão',
    role: 'dep_estadual' as const,
    party: 'PT',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - PT',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Elenil da Penha',
    role: 'dep_estadual' as const,
    party: 'MDB',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - MDB',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Nilton Franco',
    role: 'dep_estadual' as const,
    party: 'PL',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - PL',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Vilmar de Oliveira',
    role: 'dep_estadual' as const,
    party: 'Republicanos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - Republicanos',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Cleiton Cardoso',
    role: 'dep_estadual' as const,
    party: 'Republicanos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - Republicanos',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Márcia da Cáritas',
    role: 'dep_estadual' as const,
    party: 'PT',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputada Estadual do Tocantins - PT',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Luana Ribeiro',
    role: 'dep_estadual' as const,
    party: 'PSD',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputada Estadual do Tocantins - PSD',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Amilton Filho',
    role: 'dep_estadual' as const,
    party: 'MDB',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual do Tocantins - MDB',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },

  // ==================== VEREADORES DE PALMAS ====================
  {
    name: 'Marilon Barbosa',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas - Presidente da Câmara Municipal',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Marcos Júnior',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas - Vice-Presidente da Câmara Municipal',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Thiago Borges',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas - 1º Secretário da Câmara Municipal',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Zé Branquim',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Dr. Vinicius Pires',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Alex Mascarenhas',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Balaio',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Carlos Amastha',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Débora Guedes',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereadora de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Delma Freitas',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereadora de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Dian Carlos',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Eudes Assis',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas (Suplente)',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Folha',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Joatan de Jesus',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Josmundo Vila Nova',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Juarez Rigol',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Karina Café',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereadora de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Marcio Reis',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'MaryCats da Causa Animal',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereadora de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Professora Iolanda Castro',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereadora de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Rubens Uchôa',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Thamires do Coletivo Somos',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereadora de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Waldson da Agesp',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas (Licenciado)',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
  {
    name: 'Walter Viana',
    role: 'vereador' as const,
    party: null,
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas',
    photo_url: null,
    score: 0,
    total_votes: 0,
    active: true,
  },
];

export async function seedPoliticians() {
  for (const data of politiciansData) {
    await Politician.findOrCreate({ where: { name: data.name }, defaults: data });
  }
  console.log(`Seed de políticos concluído: ${politiciansData.length} registros.`);
}
