import Politician from '../models/Politician';

const politiciansData = [
  {
    name: 'Wanderlei Barbosa',
    role: 'governador' as const,
    party: 'Republicanos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Governador do Estado do Tocantins desde 2022. Anteriormente foi vice-governador e tem longa trajetória na política tocantinense.',
    photo_url: null,
    score: 62.5,
    total_votes: 1847,
    active: true,
  },
  {
    name: 'Eduardo Gomes',
    role: 'senador' as const,
    party: 'PL',
    city: 'Palmas',
    state: 'TO',
    bio: 'Senador pelo Tocantins, líder do governo no Congresso Nacional. Atua nas áreas de infraestrutura e desenvolvimento regional.',
    photo_url: null,
    score: 55.3,
    total_votes: 1203,
    active: true,
  },
  {
    name: 'Dorinha Seabra',
    role: 'dep_federal' as const,
    party: 'União Brasil',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputada Federal pelo Tocantins, especialista em educação. Relatora de projetos importantes na Comissão de Educação da Câmara.',
    photo_url: null,
    score: 71.8,
    total_votes: 956,
    active: true,
  },
  {
    name: 'Carlos Henrique Gaguim',
    role: 'dep_federal' as const,
    party: 'União Brasil',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Federal, ex-prefeito de Palmas. Foco em desenvolvimento urbano e infraestrutura para o Tocantins.',
    photo_url: null,
    score: 43.2,
    total_votes: 782,
    active: true,
  },
  {
    name: 'Cinthia Ribeiro',
    role: 'prefeito' as const,
    party: 'PSDB',
    city: 'Palmas',
    state: 'TO',
    bio: 'Prefeita de Palmas, capital do Tocantins. Primeira mulher eleita para o cargo na história da cidade.',
    photo_url: null,
    score: 58.7,
    total_votes: 2341,
    active: true,
  },
  {
    name: 'Irajá Abreu',
    role: 'senador' as const,
    party: 'PSD',
    city: 'Palmas',
    state: 'TO',
    bio: 'Senador pelo Tocantins, filho da ex-senadora Kátia Abreu. Atua nas comissões de Agricultura e Infraestrutura.',
    photo_url: null,
    score: 38.9,
    total_votes: 1105,
    active: true,
  },
  {
    name: 'Lázaro Botelho',
    role: 'dep_federal' as const,
    party: 'PP',
    city: 'Gurupi',
    state: 'TO',
    bio: 'Deputado Federal pelo Tocantins, com base eleitoral no sul do estado. Defende pautas do agronegócio e infraestrutura rural.',
    photo_url: null,
    score: 47.1,
    total_votes: 634,
    active: true,
  },
  {
    name: 'Eli Borges',
    role: 'dep_federal' as const,
    party: 'PL',
    city: 'Araguaína',
    state: 'TO',
    bio: 'Deputado Federal, pastor e comunicador. Representa a região norte do Tocantins com foco em pautas sociais e religiosas.',
    photo_url: null,
    score: 52.4,
    total_votes: 891,
    active: true,
  },
  {
    name: 'Wagner Rodrigues',
    role: 'prefeito' as const,
    party: 'MDB',
    city: 'Araguaína',
    state: 'TO',
    bio: 'Prefeito de Araguaína, segunda maior cidade do Tocantins. Médico de formação, foca em saúde pública e desenvolvimento urbano.',
    photo_url: null,
    score: 66.3,
    total_votes: 1567,
    active: true,
  },
  {
    name: 'Gutierres Torquato',
    role: 'prefeito' as const,
    party: 'PDT',
    city: 'Gurupi',
    state: 'TO',
    bio: 'Prefeito de Gurupi, terceira maior cidade do estado. Empresário com agenda voltada ao desenvolvimento econômico regional.',
    photo_url: null,
    score: 54.8,
    total_votes: 923,
    active: true,
  },
  {
    name: 'Júnior Geo',
    role: 'dep_estadual' as const,
    party: 'PSDB',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual, presidente da Assembleia Legislativa do Tocantins. Atua em pautas de governança e transparência.',
    photo_url: null,
    score: 49.5,
    total_votes: 445,
    active: true,
  },
  {
    name: 'Léo Barbosa',
    role: 'dep_estadual' as const,
    party: 'Republicanos',
    city: 'Palmas',
    state: 'TO',
    bio: 'Deputado Estadual, líder do governo na Assembleia. Foco em projetos de infraestrutura e desenvolvimento social.',
    photo_url: null,
    score: 44.2,
    total_votes: 378,
    active: true,
  },
  {
    name: 'Ivory de Lira',
    role: 'dep_estadual' as const,
    party: 'PL',
    city: 'Porto Nacional',
    state: 'TO',
    bio: 'Deputado Estadual com base em Porto Nacional. Defende pautas do agronegócio e desenvolvimento do interior do estado.',
    photo_url: null,
    score: 41.7,
    total_votes: 312,
    active: true,
  },
  {
    name: 'Amália Santana',
    role: 'vereador' as const,
    party: 'PT',
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereadora de Palmas, defensora dos direitos das mulheres e minorias. Atua em pautas de assistência social e educação.',
    photo_url: null,
    score: 73.4,
    total_votes: 567,
    active: true,
  },
  {
    name: 'Diogo Fernandes',
    role: 'vereador' as const,
    party: 'PSD',
    city: 'Palmas',
    state: 'TO',
    bio: 'Vereador de Palmas, jovem político com foco em tecnologia, inovação e modernização da gestão pública municipal.',
    photo_url: null,
    score: 68.1,
    total_votes: 489,
    active: true,
  },
];

export async function seedPoliticians() {
  for (const data of politiciansData) {
    await Politician.findOrCreate({ where: { name: data.name }, defaults: data });
  }
  console.log(`Seed de políticos concluído: ${politiciansData.length} registros.`);
}
